### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by chrisberthe**
We're deprecating CircleCI and moving towards Travis CI. This adds support for this new CI system.

### CODE REVIEW

**Comment by chrisberthe** [comment]
I removed the `yarn build` script right before you reviewed the PR 😛.

I'm not familiar with it either; first time I'm using it but it seems pretty straightforward. For breaking the build to see if it's working, we could add something to a file that will go against the rules of the tests. I do see the tests running fine in Travis CI:

image

But I'll break a test to see if it's working :')

**Comment by chrisberthe** [comment]
Also, if you both could let me know if you want to be part of the email notification list: https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications - right now I'm getting all the build emails.

We could also just disable email notifications entirely.

**Comment by chrisberthe** [comment]
image

It's working! :')

**Comment by tauthomas01** [comment]
Looks good to me!

**Pull request merged**
